### ISSUE TITLE
First parentheses' color

### ISSUE THREAD

**Issue by bounceme** [junegunn/rainbow_parentheses.vim#1]
The outermost parentheses color can be sometimes very close to the color of the background when loading a new color scheme or when reloading a vim session.

**Comment by junegunn** [comment]
I haven't experience the problem although I don't use solarized so I'm not sure about that one.
See the screenshots here: http://junegunn.kr/2014/11/rainbow-parentheses/

Anyway, I added `g:rainbow#blacklist` variable today, you can set it to be the list of colors you don't want to use. I also added `:RainbowParenthesesColors` command that can be helpful for setting it up.

1. `:RainbowParenthesesColors` to see the colors chosen that are not very readable
2. Build `g:rainbow#blacklist` list containing the value of ctermfg or guifg of the colors you want to exclude
3. `:RainbowParentheses` to reinitialize colors
4. Check the output of `:RainbowParenthesesColors`

**Comment by bounceme** [comment]
I think it's probably because I don't actually define my color scheme in my vimrc, but let the color persist with sessions. I'll be able to fix this for myself though so thank you

**Comment by bounceme** [comment]
This seems to be caused by changing to and from files with ctrlp too.

**Comment by junegunn** [comment]
Yeah, I can reproduce, ctrl-p seems to define a highlight group that has the same foreground color as the background. I can prevent this by setting up `g:rainbow#blacklist`. But I think it's better to allow such colors in the first place.

**Comment by junegunn** [comment]
I updated the code so that it does not pick invisible. Thanks.

**Comment by bounceme** [comment]
Nice.Thanks!
