### ISSUE TITLE
Curly braces ( { and } ) not working

### ISSUE THREAD

**Issue by garymh** [junegunn/rainbow_parentheses.vim#10]
Hi @junegunn! Love the plugin, but I can't seem to get curly braces to work. I currently have this in my vimrc:

``` VimL
let g:rainbow#pairs = [['(', ')'], ['[', ']'], ['{', '}']]
```

Is that the correct way to add a set of symbols?

**Comment by junegunn** [comment]
Yeah. But I've noticed that it may not work depending on the syntax of the file type. Not sure if there's a surefire solution. You'll see that the config works if you open an empty buffer with no file type and enable rainbow parens.

**Comment by garymh** [comment]
Ah, yeah - doesn't seem to. Ok, no prob! I was just curious.
