### ISSUE TITLE
Can't seem to get it working at all.

### ISSUE THREAD

**Issue by cyfyifanchen** [junegunn/rainbow_parentheses.vim#12]
dude, all of your plugins are working prefect for me. However, I can't seem get this one working for some reasons. I have tried different file types, i.e. `.js`, `.less` ect.

**Comment by junegunn** [comment]
Unfortunately this plugin is known to be incompatible with some file types. I only use it with lisp languages, so I haven't investigated if it's possible to fix that.

**Comment by cyfyifanchen** [comment]
I see.
