### ISSUE TITLE
RainbowParentheses in vimrc

### ISSUE THREAD

**Issue by themightyoarfish** [junegunn/rainbow_parentheses.vim#13]
When I put `RainbowParentheses` (same with `Limelight`) at the very end of my `.vimrc` after `let g:limelight_conceal_ctermfg = 240` I get `not an editor command` for both at startup, while it works when vim is already open. 
Why could this be?

**Comment by OleMussmann** [comment]
As taken from here: [https://github.com/kien/rainbow_parentheses.vim](https://github.com/kien/rainbow_parentheses.vim) you have to use
`au VimEnter * RainbowParentheses`
If I understood correctly, this uses `autocommand` to execute stuff when entering vim.

**Comment by junegunn** [comment]
@OleMussmann is correct. Vim plugins are loaded after Vim finished processing vimrc, so they are not available at the point (see `:help startup`). So you should set up an autocmd such as VimEnter and FileType.

**Comment by themightyoarfish** [comment]
Do I set these up in the `.vimrc`? Because if I do that, it still gives me those errors.
