### ISSUE TITLE
Only highlight surrounding parentheses?

### ISSUE THREAD

**Issue by anntzer** [junegunn/rainbow_parentheses.vim#15]
emacs' highlight-parentheses (https://www.emacswiki.org/emacs/HighlightParentheses) *only* color-highlights all pairs of delimiters that are surrounding the current cursor position, using different colors for different levels.  Would it be possible to provide a similar behavior in this plugin?

(As far as I can see there is no plugin that provides this behavior for vim right now; the closest I have found is https://github.com/justinmk/vim-matchparenalways, which only highlights the closest surrounding pair.)

Thanks in advance.

**Comment by thaerkh** [comment]
@anntzer a few weeks ago I made a pull request that provides this behaviour (https://github.com/junegunn/rainbow_parentheses.vim/pull/14).
It's up to @junegunn as to whether or not the pull request's accepted. In the mean time, the commit is available in this fork https://github.com/thaerkh/rainbow_parentheses.vim

**Comment by lervag** [comment]
There was a discussion on reddit about this, recently, see [here](https://www.reddit.com/r/vim/comments/5rdxq3/looking_for_an_equivalent_of_emacs/). I would also be interested in using a good rainbow-parantheses plugin that only highlights actually surrounding parantheses, and think this would be a very good addition to this plugin.

**Comment by anntzer** [comment]
@lervag https://github.com/bounceme/poppy.vim (which was published after I started the reddit thread) works very well for me.  I use the colors of https://github.com/losingkeys/vim-niji, which are quite flashy, but much more visible (and that's sort of the point...) than the rest of my preferred colorscheme (zenburn), which is very low contrast.  I also use the mapping given in the README.

**Comment by junegunn** [comment]
Glad to hear that you found the solution. I personally don't need it and have no plan to work on it, so let me close the issue.
