### ISSUE TITLE
Whitelist Option? 

### ISSUE THREAD

**Issue by her** [junegunn/rainbow_parentheses.vim#16]
Example: If I only want to use 16 colors (in a term with 256) a whitelist would be much easier to configure rather than a blacklist... 

Side question: Is it possible to supply a range of numbers in `let g:rainbow#blacklist`? 

Thanks for the great plugins, Junegunn. I'm using several of them 😄 🙏

**Comment by junegunn** [comment]
You can use this:

```vim
let g:rainbow#blacklist = range(16, 255)
```

**Comment by her** [comment]
That's great, thanks Junegunn!!! 🙏 🎉
