### ISSUE TITLE
Problem with javascript

### ISSUE THREAD

**Issue by bounceme** [junegunn/rainbow_parentheses.vim#2]
When using the syntax from here:
https://github.com/jelera/vim-javascript-syntax

the matching is disrupted when there is a iife or a callback function as an argument.This doesn't happen with the default syntax

**Comment by junegunn** [comment]
Thanks. Yeah, I also noticed that this doesn't work with some syntaxes. Since I only use it for lisps, it doesn't bother me. But pull requests are appreciated.
