### ISSUE TITLE
Using Rainbow Parenthesis

### ISSUE THREAD

**Issue by pickfire** [junegunn/rainbow_parentheses.vim#4]
I hope you can add the usage of Rainbow Parenthesis in README.md.

And can I use `call rainbowparenthesis` to enable Rainbow Parenthesis in ~/.vimrc?

**Comment by junegunn** [comment]
The README page already has enough information to get you started. 

> call rainbowparenthesis

Where did you get that? Just use the commands shown in the README page.

**Comment by pickfire** [comment]
What about auto intialization?

**Comment by junegunn** [comment]
It's also on the page.

**Comment by pickfire** [comment]
```vim
" Activation based on file type
augroup rainbow_lisp
  autocmd!
  autocmd FileType lisp,clojure,scheme RainbowParentheses
augroup END
```
It doesn't show how to use RainbowParentheses for all time and I found out that using autocommand seems a bit slow for plugins.
