### ISSUE TITLE
Enable globally?

### ISSUE THREAD

**Issue by Quintasan** [junegunn/rainbow_parentheses.vim#5]
Hi,

I'm using `vim-plug` and I want the rainbow_parentheses to be enabled for any kind of file without me manually invoking any command, is this somehow possible? What I'm currently doing is
`````
call plug#load('rainbow_parentheses.vim')
call rainbow_parentheses#activate()
``````
which seems hacky to say the least

**Comment by junegunn** [comment]
Something like this?
```vim
augroup rainbow_parens
  autocmd!
  autocmd Syntax * RainbowParentheses
augroup END
```
But I don't recommend it as this plugin does not work with some filetypes.
