### ISSUE TITLE
Error with .cfg file

### ISSUE THREAD

**Issue by DavidGamba** [junegunn/rainbow_parentheses.vim#6]
When using a file with extension `.cfg` and neovim's default colorscheme I get the following error:

![rainbow-error](https://cloud.githubusercontent.com/assets/1115287/9411779/4d870012-47e5-11e5-8cd3-361a0a504e1e.png)

Is there a way to avoid these errors?
A fallback to no color instead of a warning?

I was starting rainbow parentheses by using:

````vim
Plug 'junegunn/rainbow_parentheses.vim'
autocmd VimEnter * RainbowParentheses
let g:rainbow#pairs = [['(', ')'], ['[', ']']]
````

but now I have this to avoid it:

````vim
Plug 'junegunn/rainbow_parentheses.vim'
let rainbow_blacklist = ['cfg']
autocmd VimEnter * if index(rainbow_blacklist, &ft) < 0 | RainbowParentheses
let g:rainbow#pairs = [['(', ')'], ['[', ']']]
````

Thanks!

**Comment by junegunn** [comment]
Interesting, it also happens with Vim. I'll look into it.

**Comment by junegunn** [comment]
It should be fixed now, let me know if you still see the errors. Thanks.

**Comment by DavidGamba** [comment]
Wow, that was fast! thanks :-) It works now :+1:
