### ISSUE TITLE
Overwrite automatic colors with predefined ones

### ISSUE THREAD

**Issue by hoschi** [junegunn/rainbow_parentheses.vim#7]
Hi,

great plugin! It is the only one which works with neovims true color mode and javascript syntax plugin!
I want to define colors for parentheses levels by hand, to make them more outstanding. Automatic colors makes parentheses look like other words, especially when using semantic highlight. My VimL is not good enough to check how to do this when looking into the plugin sources. I tried already to add `hi rainbowParensShell1 guifg=#ff0000` to my .nvimrc but this didn't do the trick :(

**Comment by junegunn** [comment]
You can try setting `g:rainbow#colors`. I intentionally removed it from README page a while ago because I felt it was no longed needed, but it's still functional.

```vim
let g:rainbow#colors = {
\   'dark': [
\     ['yellow',  'orange1'     ],
\     ['green',   'yellow1'     ],
\     ['cyan',    'greenyellow' ],
\     ['magenta', 'green1'      ],
\     ['red',     'springgreen1'],
\     ['yellow',  'cyan1'       ],
\     ['green',   'slateblue1'  ],
\     ['cyan',    'magenta1'    ],
\     ['magenta', 'purple1'     ]
\   ],
\   'light': [
\     ['darkyellow',  'orangered3'    ],
\     ['darkgreen',   'orange2'       ],
\     ['blue',        'yellow3'       ],
\     ['darkmagenta', 'olivedrab4'    ],
\     ['red',         'green4'        ],
\     ['darkyellow',  'paleturquoise3'],
\     ['darkgreen',   'deepskyblue4'  ],
\     ['blue',        'darkslateblue' ],
\     ['darkmagenta', 'darkviolet'    ]
\   ]
\ }
```

**Comment by hoschi** [comment]
this works, thank you!
